# Generated by Django 5.1.5 on 2025-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
        ('product', '0002_product_deleted_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(to='imageupload.imageupload'),
        ),
    ]
