# Generated by Django 5.1.5 on 2025-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='contact_number',
            field=models.CharField(default='09909090909', max_length=16),
            preserve_default=False,
        ),
    ]
